image:
  file: docker/gitpod/Dockerfile

ports:
  - port: 3000
    onOpen: "open-browser"
    visibility: "public"

tasks:
  - name: "Start redis-server"
    command: "redis-server"
  - name: "Start crusher app"
    init: yarn install && yarn setup:ee && cp ecosystem.config.sample.js ecosystem.config.js && rm .env && cp .env.gitpod .env && mysql -uroot -e "CREATE DATABASE crusher /*\!40100 DEFAULT CHARACTER SET utf8 */;" && DB_USERNAME=root yarn db:migration
    command: "pm2 start --only='crusher-server' && yarn workspace crusher-app dev"
    openMode: split-right
