image:
  file: docker/gitpod/Dockerfile

ports:
  - port: 3000
    onOpen: "open-browser"
    visibility: "public"

tasks:
  - name: "Initial Setup"
    init: yarn install && yarn setup:ee
  - name: "Start redis-server"
    command: "redis-server"
    openMode: split-right
  - name: "Start crusher app"
    command: "cd packages/crusher-app && yarn dev"
    openMode: split-right
