image:
  file: docker/gitpod/Dockerfile

ports:
  - port: 3000
    onOpen: "open-browser"
    visibility: "public"

tasks:
  - name: "Start redis-server"
    command: "redis-server"
  - name: "Start crusher app"
    init: yarn install && yarn setup:ee
    command: "yarn workspace crusher-app dev"
    openMode: split-right
