version: '2.2'
services:
  oss_container1:
    build:
      context: ../../
      dockerfile: docker/oss/Dockerfile
    network_mode: host
    environment:
      - LOGDNA_API_KEY=c7bdd500e3cfbfe457a2ec4168b8cfaa
      - DB_HOST=db-mysql-nyc3-51235-do-user-9421575-0.b.db.ondigitalocean.com
      - DB_USERNAME=doadmin
      - DB_PASSWORD=c1y6sb2379tx2alr
      - DB_PORT=25060
      - MONGODB_CONNECTION_STRING=mongodb://localhost:27017/crusher
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - BACKEND_SERVER_URL=http://localhost:3000/server
      - NEXT_PUBLIC_CRUSHER_MODE=open-source
      - NEXT_PUBLIC_INTERNAL_BACKEND_URL=http://localhost:3000/server
    container_name: 'oss1'
    stdin_open: true # docker run -i
    tty: true