name: Build Electron App

on:
  release:
    types: [published, edited]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.19.1

      - name: Install yarn
        run: npm install -g yarn

      - name: Use cache for yarn if available
        uses: c-hive/gha-yarn-cache@v1

      - name: Create ecosystem.config.js
        run: cp ecosystem.config.sample.js ecosystem.config.js

      - name: Copy .env.sample file
        run: cp .env.sample .env

      - name: Install crusher modules
        run: yarn

      - name: Setup crusher for prod
        run: yarn setup:prod

      - name: Build release for electron app
        run: yarn workspace crusher-electron-app release:all

      - name: Install zip
        run: sudo apt-get install zip

      - name: 'Store crusher-darwin as artifact'
        uses: actions/upload-artifact@v2
        with:
          name: crusher-darwin
          path: output/crusher-electron-app-release/crusher-darwin.zip
          retention-days: 5

      - name: 'Store crusher-linux as artifact'
        uses: actions/upload-artifact@v2
        with:
          name: crusher-linux
          path: output/crusher-electron-app-release/crusher-linux.zip
          retention-days: 5
