name: Build OSS docker-image

on:
  push:
    branches: [ master ]
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.4

      - name: Install yarn
        run: npm install -g yarn

      - name: Use cache for yarn if available
        uses: c-hive/gha-yarn-cache@v1

      - name: Create ecosystem.config.js
        run: cp ecosystem.config.sample.js ecosystem.config.js

      - name: Copy .env.sample file
        run: cp .env.sample .env

      - name: Install crusher modules
        run: yarn

      - name: Setup crusher for oss
        run: yarn setup:oss

      - name: Install webpack
        run: npm install -g webpack

      - name: Upgrade heap size of node
        run: export NODE_OPTIONS=--max_old_space_size=4096

      - name: Build all packages
        run: sh scripts/build/build-oss.sh
        env:
          NODE_OPTIONS: --max_old_space_size=8048

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/oss/Dockerfile
          context: .
          push: true
          tags: crusherdev/crusher:oss1.0
        env:
          DOCKER_BUILDKIT: 1
